# AnyPerp production image (Node production server via vinext start)
FROM node:22-bookworm-slim

WORKDIR /app
RUN corepack enable && corepack prepare pnpm@11.13.0 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY services ./services
COPY app ./app
COPY public ./public
COPY scripts ./scripts
COPY contracts ./contracts
COPY database ./database
COPY build ./build
COPY worker ./worker
COPY vite.config.ts next.config.ts tsconfig.json postcss.config.mjs eslint.config.mjs foundry.toml ./
COPY .openai ./.openai

RUN pnpm install --frozen-lockfile

# Build-time public env (overridden at runtime for NEXT_PUBLIC via rebuild if needed)
ARG NEXT_PUBLIC_CHAIN_ID=46630
ARG NEXT_PUBLIC_RPC_URL=https://rpc.testnet.chain.robinhood.com
ARG NEXT_PUBLIC_SITE_URL=https://anyperp.fun
ARG NEXT_PUBLIC_DOCS_URL=https://anyperp.fun/?surface=docs
ARG NEXT_PUBLIC_APP_URL=https://anyperp.fun/?surface=app
ARG NEXT_PUBLIC_MARKET_FACTORY_ADDRESS
ARG NEXT_PUBLIC_MARKET_REGISTRY_ADDRESS
ARG NEXT_PUBLIC_ORACLE_ROUTER_ADDRESS
ARG NEXT_PUBLIC_LIQUIDATION_ENGINE_ADDRESS
ARG NEXT_PUBLIC_TRIGGER_ORDER_MANAGER_ADDRESS
ARG NEXT_PUBLIC_COLLATERAL_ADDRESS
ARG NEXT_PUBLIC_MARKET_LENS_ADDRESS
ARG NEXT_PUBLIC_DEMO_MARKET_ADDRESS
ARG NEXT_PUBLIC_DEMO_MARKET_ID
ARG NEXT_PUBLIC_DEMO_BASE_TOKEN
ARG NEXT_PUBLIC_DEMO_ORACLE_ROUTE_ID
ARG NEXT_PUBLIC_DEMO_LIQUIDITY_VAULT
ARG NEXT_PUBLIC_DEMO_INSURANCE_FUND
ARG NEXT_PUBLIC_API_URL=https://anyperp.fun

ENV NEXT_PUBLIC_CHAIN_ID=$NEXT_PUBLIC_CHAIN_ID \
    NEXT_PUBLIC_RPC_URL=$NEXT_PUBLIC_RPC_URL \
    NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_DOCS_URL=$NEXT_PUBLIC_DOCS_URL \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_MARKET_FACTORY_ADDRESS=$NEXT_PUBLIC_MARKET_FACTORY_ADDRESS \
    NEXT_PUBLIC_MARKET_REGISTRY_ADDRESS=$NEXT_PUBLIC_MARKET_REGISTRY_ADDRESS \
    NEXT_PUBLIC_ORACLE_ROUTER_ADDRESS=$NEXT_PUBLIC_ORACLE_ROUTER_ADDRESS \
    NEXT_PUBLIC_LIQUIDATION_ENGINE_ADDRESS=$NEXT_PUBLIC_LIQUIDATION_ENGINE_ADDRESS \
    NEXT_PUBLIC_TRIGGER_ORDER_MANAGER_ADDRESS=$NEXT_PUBLIC_TRIGGER_ORDER_MANAGER_ADDRESS \
    NEXT_PUBLIC_COLLATERAL_ADDRESS=$NEXT_PUBLIC_COLLATERAL_ADDRESS \
    NEXT_PUBLIC_MARKET_LENS_ADDRESS=$NEXT_PUBLIC_MARKET_LENS_ADDRESS \
    NEXT_PUBLIC_DEMO_MARKET_ADDRESS=$NEXT_PUBLIC_DEMO_MARKET_ADDRESS \
    NEXT_PUBLIC_DEMO_MARKET_ID=$NEXT_PUBLIC_DEMO_MARKET_ID \
    NEXT_PUBLIC_DEMO_BASE_TOKEN=$NEXT_PUBLIC_DEMO_BASE_TOKEN \
    NEXT_PUBLIC_DEMO_ORACLE_ROUTE_ID=$NEXT_PUBLIC_DEMO_ORACLE_ROUTE_ID \
    NEXT_PUBLIC_DEMO_LIQUIDITY_VAULT=$NEXT_PUBLIC_DEMO_LIQUIDITY_VAULT \
    NEXT_PUBLIC_DEMO_INSURANCE_FUND=$NEXT_PUBLIC_DEMO_INSURANCE_FUND \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN pnpm build

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000

CMD ["pnpm", "start"]
