packages:
  - "packages/*"
  - "services/*"
allowBuilds:
  bufferutil: true
  esbuild: true
  keccak: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  workerd: true
